services:
#    cms_core.example:
#        class: CMS\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.media.resizer.custom:
        class: CMS\CoreBundle\Image\CustomResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]