info_gallery_video:
    path:     /test/video
    defaults: { _controller: InfoGalleryBundle:VideoGallery:video }


info_gallery_video_list:
    path:     /videos
    defaults: { _controller: InfoGalleryBundle:VideoGallery:videos }


info_gallery_photo_list:
    path:     /photos
    defaults: { _controller: InfoGalleryBundle:PhotoGallery:photos }

info_gallery_album_get:
    path:     /album/get/{id}
    defaults: { _controller: InfoGalleryBundle:PhotoGallery:getAlbum }

