services:
#    info_news.example:
#        class: Info\NewsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    info_news.admin.news:
        class: Info\NewsBundle\Admin\NewsAdmin
        arguments: [~, Info\NewsBundle\Entity\News, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News}
